---
abstract: 'parse directory listing using ftpparse from ftpcopy'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  POSIX: 0
  Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Listing-Ftpcopy
requires:
  perl: v5.10.1
resources:
  bugtracker: https://github.com/plicease/file-listing-ftpcopy/issues
  homepage: http://perl.wdlabs.com/File-Listing-Ftpcopy/
  repository: git://github.com/plicease/file-listing-ftpcopy.git
version: 0.02_02
